"""Generate a default ``wsprdaemon.conf`` (v4 INI) from sigmond's
coordination.toml.

Called by ``bin/wd-config-init`` (advertised in ``deploy.toml`` as the
``[contract.config].init`` entry point) so ``smd config init
wsprdaemon-client`` produces a useful starting config without any
hand-editing for the common single-host single-RX-888 setup.

What the generator does:

  * Read every ``[radiod.<id>]`` block in
    ``/etc/sigmond/coordination.toml`` whose ``host`` is local.
  * For each, emit a ``[receiver:KA9Q_<n>]`` block with
    ``radiod_name = <id>``.  The receiver's ``call``/``grid`` are
    deliberately omitted — they fall back through ``[general]
    .reporter_call`` → ``$STATION_CALL`` (CONTRACT-v0.5 §14.2),
    so the operator never types a callsign that sigmond already knows.
  * Emit per-band ``[receiver:<name>:<band>]`` blocks that cover
    every WSPR band the upstream parser knows about (``2200`` through
    ``10`` per ``BAND_FREQ_HZ``):
      - On ``2200`` and ``630``, modes ``W2 F2 F5 F15 F30`` —
        the long FST4W windows that the slow LF/MF QSB rewards.
      - On every other band, modes ``W2 F2 F5`` — standard
        2-minute WSPR + 2- and 5-minute FST4W.
  * One ``[schedule:default]`` block listing all bands per receiver
    so the entire band plan is active 24/7.

The function refuses to overwrite an existing wsprdaemon.conf unless
``force=True``.  Callers should surface that to the operator with a
clear "use --force to regenerate" hint rather than silently clobbering.
"""

from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


# Bands the upstream parser recognises (see envgen.BAND_FREQ_HZ); listed
# in operator-friendly low→high order so the rendered conf reads naturally.
WSPR_BANDS_DEFAULT: tuple[str, ...] = (
    '2200', '630',                             # LF / MF
    '160', '80', '60', '40', '30', '22',       # HF low + middle
    '20', '17', '15', '12', '10',              # HF high
)

# Modes per band class.  Long-window FST4W (F15, F30) added on
# LF/MF because that's where slow propagation makes them earn their keep.
LONG_WINDOW_BANDS: frozenset[str] = frozenset({'2200', '630'})
DEFAULT_MODES_LF_MF: tuple[str, ...] = ('W2', 'F2', 'F5', 'F15', 'F30')
DEFAULT_MODES_HF:    tuple[str, ...] = ('W2', 'F2', 'F5')


@dataclass(frozen=True)
class _LocalRadiod:
    instance_id: str
    status_dns:  str
    sdr_serial:  str


def _load_local_radiods(coord_path: Path) -> list[_LocalRadiod]:
    """Return all `[radiod.<id>]` entries whose host is local."""
    if not coord_path.exists():
        return []
    with open(coord_path, 'rb') as f:
        raw = tomllib.load(f)
    out: list[_LocalRadiod] = []
    for rid, rcfg in (raw.get('radiod', {}) or {}).items():
        rcfg = rcfg or {}
        host = (rcfg.get('host') or 'localhost').strip()
        if host not in ('localhost', '127.0.0.1', '::1', ''):
            continue
        out.append(_LocalRadiod(
            instance_id=rid,
            status_dns=str(rcfg.get('status_dns') or '').strip(),
            sdr_serial=str(rcfg.get('sdr_serial') or '').strip(),
        ))
    return out


def _modes_for(band: str) -> tuple[str, ...]:
    return DEFAULT_MODES_LF_MF if band in LONG_WINDOW_BANDS else DEFAULT_MODES_HF


def render_default_conf(radiods: list[_LocalRadiod],
                        bands: tuple[str, ...] = WSPR_BANDS_DEFAULT) -> str:
    """Render a v4 INI for the given list of local radiods + a default band plan."""
    lines: list[str] = [
        '# /etc/wsprdaemon/wsprdaemon.conf',
        '# Generated by wd-config-init from /etc/sigmond/coordination.toml.',
        '#',
        '# Operator identity is published by sigmond via STATION_CALL /',
        '# STATION_GRID; leaving [general].reporter_call empty tells the',
        '# v4 parser to fall back through the env-var bag (CONTRACT v0.5',
        '# §14.2).  Per-receiver call/grid are similarly omitted.',
        '#',
        '# Re-run `smd config init wsprdaemon-client --force` after',
        '# adding/removing radiod instances in coordination.toml — this',
        '# file is regenerated, so any hand edits below will be lost.',
        '',
        '[general]',
    ]

    # ka9q_conf_name traditionally points at one radiod (the "primary")
    # for legacy v3 helpers that read it.  Use the first registered local
    # radiod by declaration order; multi-radiod hosts mostly don't care.
    if radiods:
        lines.append(f'ka9q_conf_name = {radiods[0].instance_id}')
    lines.append('')

    receiver_names: list[str] = []
    for n, r in enumerate(radiods):
        rx_name = f'KA9Q_{n}'
        receiver_names.append(rx_name)
        lines.append(f'[receiver:{rx_name}]')
        lines.append('type        = ka9q')
        lines.append('locality    = local')
        lines.append(f'radiod_name = {r.instance_id}')
        if r.status_dns:
            lines.append(f'# status_dns  = {r.status_dns}    # informational; bound by radiod_name above')
        lines.append('# call, grid: omitted — fall back through STATION_CALL / STATION_GRID')
        lines.append('')

        # Long-window FST4W on LF/MF, standard set on HF — one [receiver:NAME:BAND] each.
        for band in bands:
            modes = _modes_for(band)
            lines.append(f'[receiver:{rx_name}:{band}]')
            lines.append(f'modes = {" ".join(modes)}')
            lines.append('')

    if receiver_names:
        lines.append('[schedule:default]')
        lines.append('time = 00:00')
        for rx_name in receiver_names:
            lines.append(f'{rx_name} = {" ".join(bands)}')
        lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def init_config(
    *,
    coord_path:  Path = Path('/etc/sigmond/coordination.toml'),
    output_path: Path = Path('/etc/wsprdaemon/wsprdaemon.conf'),
    force:       bool = False,
    bands:       tuple[str, ...] = WSPR_BANDS_DEFAULT,
) -> tuple[bool, str]:
    """Generate /etc/wsprdaemon/wsprdaemon.conf with sigmond-aware defaults.

    Returns (ok, message).  Refuses if the output file exists and ``force``
    is False — caller surfaces the "use --force" hint.
    """
    radiods = _load_local_radiods(coord_path)
    if not radiods:
        return False, (
            f'no local radiods declared in {coord_path}; '
            f'run `smd config init radiod` first to register one'
        )

    if output_path.exists() and not force:
        return False, (
            f'{output_path} already exists; pass --force to regenerate '
            f'(any local edits will be lost)'
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_default_conf(radiods, bands=bands))

    summary = (
        f'wrote {output_path}: {len(radiods)} receiver(s) '
        f'({", ".join(r.instance_id for r in radiods)}), '
        f'{len(bands)} bands ({bands[0]}m..{bands[-1]}m)'
    )
    return True, summary
