"""Environment file and systemd drop-in generator for wsprdaemon v4.

Reads parsed configuration (either from v3 migration or v4 INI) and
generates:
  - /etc/wsprdaemon/env/wd-ka9q-record@<RX>.env
  - /etc/wsprdaemon/env/wd-kiwi-record@<RX>-<BAND>.env
  - /etc/wsprdaemon/env/wd-decode@<RX>-<BAND>.env
  - /etc/wsprdaemon/env/wd-post@<RX>-<BAND>.env

These env files are referenced by EnvironmentFile= in the systemd unit templates.
"""

import re
from pathlib import Path
from typing import Dict, List, Optional, Set

from wdlib import paths
from wdlib.v3_parser import V3Config, V3Receiver


def _read_radiod_status_dns(ka9q_conf_name: str) -> str:
    """Extract the status= DNS name from /etc/radio/radiod@<name>.conf."""
    conf = Path(f'/etc/radio/radiod@{ka9q_conf_name}.conf')
    if not conf.exists():
        return ''
    for raw in conf.read_text().splitlines():
        line = raw.strip()
        if line.startswith('#'):
            continue
        m = re.match(r'^status\s*=\s*(\S+)', line)
        if m:
            return m.group(1)
    return ''

# WSPR band center frequencies in Hz (for wsprd and jt9)
BAND_FREQ_HZ = {
    '2200':   136000,
    '630':    474200,
    '160':   1836600,
    '80':    3568600,
    '80eu':  3592600,
    '60':    5287200,
    '60eu':  5364700,
    '40':    7038600,
    '30':   10138700,
    '22':   13553900,
    '20':   14095600,
    '17':   18104600,
    '15':   21094600,
    '12':   24924600,
    '10':   28124600,
    # WWV/CHU bands (IQ recording)
    'WWV_2_5':  2500000,
    'WWV_5':    5000000,
    'WWV_10':  10000000,
    'WWV_15':  15000000,
    'WWV_20':  20000000,
    'WWV_25':  25000000,
    'CHU_3':    3330000,
    'CHU_7':    7850000,
    'CHU_14':  14670000,
}


def _env_header() -> str:
    return '# Auto-generated by wd-ctl — do not edit manually\n'


def generate_ka9q_record_env(receiver: V3Receiver,
                              bands: Set[str],
                              band_modes: Dict[str, set],
                              radiod_status_dns: str = '') -> str:
    """Generate env file for a KA9Q recording service.

    KA9Q recorders are 1-to-N: one process uses ka9q-python to dynamically
    create channels on radiod and write wav files for all component bands.
    """
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_TYPE={receiver.receiver_type}')
    lines.append(f'WD_RADIOD_STATUS={radiod_status_dns}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECORDING_DIR={paths.receiver_recording_dir(receiver.name)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_RUN_DIR={paths.RUN_DIR}')
    sorted_bands = sorted(bands, key=lambda b: BAND_FREQ_HZ.get(b, 0))
    lines.append(f'WD_BANDS={" ".join(sorted_bands)}')
    return '\n'.join(lines) + '\n'


def generate_kiwi_record_env(receiver: V3Receiver,
                              band: str,
                              modes: str) -> str:
    """Generate env file for a Kiwi recording service instance.

    Kiwi recorders are 1:1 — one kiwi_recorder.py per channel/band.
    """
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_TYPE=kiwi')
    lines.append(f'WD_KIWI_ADDRESS={receiver.address}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECEIVER_BAND={band}')
    lines.append(f'WD_RECEIVER_MODES={modes}')
    freq = BAND_FREQ_HZ.get(band, 0)
    lines.append(f'WD_RECEIVER_FREQ_HZ={freq}')
    pw = receiver.password if receiver.password != 'NULL' else ''
    lines.append(f'WD_KIWI_PASSWORD={pw}')
    lines.append(f'WD_RECORDING_DIR={paths.band_recording_dir(receiver.name, band)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_RUN_DIR={paths.RUN_DIR}')
    return '\n'.join(lines) + '\n'


def generate_decode_env(receiver: V3Receiver,
                        band: str,
                        modes: str) -> str:
    """Generate env file for a decode service instance."""
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_TYPE={receiver.receiver_type}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECEIVER_BAND={band}')
    lines.append(f'WD_RECEIVER_MODES={modes}')
    freq = BAND_FREQ_HZ.get(band, 0)
    lines.append(f'WD_RECEIVER_FREQ_HZ={freq}')
    lines.append(f'WD_RECORDING_DIR={paths.band_recording_dir(receiver.name, band)}')
    lines.append(f'WD_POSTING_DIR={paths.band_posting_dir(receiver.name, band)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_RUN_DIR={paths.RUN_DIR}')
    return '\n'.join(lines) + '\n'


def generate_post_env(receiver: V3Receiver,
                      band: str,
                      modes: str,
                      upload_wsprnet: bool = True,
                      upload_wsprdaemon: bool = True) -> str:
    """Generate env file for a posting service instance."""
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECEIVER_BAND={band}')
    lines.append(f'WD_POSTING_DIR={paths.band_posting_dir(receiver.name, band)}')
    if upload_wsprnet:
        lines.append(f'WD_UPLOAD_WSPRNET_DIR={paths.upload_dir("wsprnet", receiver.call, receiver.grid)}')
    if upload_wsprdaemon:
        lines.append(f'WD_UPLOAD_WSPRDAEMON_DIR={paths.upload_dir("wsprdaemon", receiver.call, receiver.grid, receiver.name, band)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    return '\n'.join(lines) + '\n'


def generate_all_env_files(config: V3Config, output_dir: Path) -> List[str]:
    """Generate all environment files from a parsed v3 config.

    Returns a list of file paths that were written.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    written = []

    # Collect which receivers actually appear in the schedule
    # and what bands/modes they use
    rx_band_modes: Dict[str, Dict[str, str]] = {}  # rx_name → {band → modes_str}

    for slot in config.schedule_slots:
        for entry in slot.entries:
            rx_name = entry.receiver
            if rx_name not in rx_band_modes:
                rx_band_modes[rx_name] = {}
            # Keep the fullest mode list seen
            existing = rx_band_modes[rx_name].get(entry.band, '')
            existing_set = set(existing.split(':')) if existing else set()
            new_set = set(entry.modes.split(':'))
            combined = existing_set | new_set
            rx_band_modes[rx_name][entry.band] = ':'.join(sorted(combined))

    # Expand merge sources: every band assigned to a merge receiver must also
    # be recorded by each component source receiver.  The merge only happens
    # after decoding — all sources record independently.
    for rx_name in list(rx_band_modes.keys()):
        rx = config.receivers.get(rx_name)
        if rx is None or not rx.is_merge:
            continue
        for src_name in rx.merge_sources:
            src_rx = config.receivers.get(src_name)
            if src_rx is None:
                continue
            if src_name not in rx_band_modes:
                rx_band_modes[src_name] = {}
            for band, modes in rx_band_modes[rx_name].items():
                existing = rx_band_modes[src_name].get(band, '')
                existing_set = set(existing.split(':')) - {''} if existing else set()
                new_set = set(modes.split(':')) - {''}
                rx_band_modes[src_name][band] = ':'.join(sorted(existing_set | new_set))

    # Read the radiod status DNS once from the site radiod config
    radiod_status_dns = _read_radiod_status_dns(config.ka9q_conf_name) if config.ka9q_conf_name else ''

    for rx_name, band_map in rx_band_modes.items():
        rx = config.receivers.get(rx_name)
        if not rx:
            continue

        if rx.receiver_type == 'ka9q':
            # KA9Q recorder — one env file per receiver
            env_path = output_dir / f'wd-ka9q-record@{rx_name}.env'
            env_path.write_text(generate_ka9q_record_env(
                rx, set(band_map.keys()), config.band_modes, radiod_status_dns
            ))
            written.append(str(env_path))

            # Decode env — one per receiver+band
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-decode@{inst}.env'
                env_path.write_text(generate_decode_env(rx, band, modes))
                written.append(str(env_path))

                env_path = output_dir / f'wd-post@{inst}.env'
                env_path.write_text(generate_post_env(rx, band, modes))
                written.append(str(env_path))

        elif rx.receiver_type == 'ka9q_wwv':
            # WWV/CHU IQ recording — one env per receiver
            env_path = output_dir / f'wd-ka9q-record@{rx_name}.env'
            env_path.write_text(generate_ka9q_record_env(
                rx, set(band_map.keys()), config.band_modes, radiod_status_dns
            ))
            written.append(str(env_path))

            # IQ decode instances
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-decode@{inst}.env'
                env_path.write_text(generate_decode_env(rx, band, modes))
                written.append(str(env_path))

        elif rx.receiver_type == 'kiwi':
            # Kiwi recorder — one env per receiver+band
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-kiwi-record@{inst}.env'
                env_path.write_text(generate_kiwi_record_env(rx, band, modes))
                written.append(str(env_path))

                env_path = output_dir / f'wd-decode@{inst}.env'
                env_path.write_text(generate_decode_env(rx, band, modes))
                written.append(str(env_path))

                env_path = output_dir / f'wd-post@{inst}.env'
                env_path.write_text(generate_post_env(rx, band, modes))
                written.append(str(env_path))

        elif rx.receiver_type == 'merge':
            # Merge receivers — decode/post env only (recording comes from sources)
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-decode@{inst}.env'
                content = generate_decode_env(rx, band, modes)
                # Add merge source list
                content += f'WD_MERGE_SOURCES={rx.address}\n'
                env_path.write_text(content)
                written.append(str(env_path))

                env_path = output_dir / f'wd-post@{inst}.env'
                env_path.write_text(generate_post_env(rx, band, modes))
                written.append(str(env_path))

    return written
