"""Environment file and systemd drop-in generator for wsprdaemon v4.

Reads parsed configuration (either from v3 migration or v4 INI) and
generates:
  - /etc/wsprdaemon/env/wd-ka9q-record@<RX>.env
  - /etc/wsprdaemon/env/wd-kiwi-record@<RX>-<BAND>.env
  - /etc/wsprdaemon/env/wd-decode@<RX>-<BAND>.env
  - /etc/wsprdaemon/env/wd-post@<RX>-<BAND>.env

These env files are referenced by EnvironmentFile= in the systemd unit templates.
"""

import re
from pathlib import Path
from typing import Dict, List, Optional, Set

from wdlib import paths
from wdlib.config import WdConfig, Receiver


def _radiod_status_dns(receiver: 'Receiver') -> str:
    """Return the status DNS name to use for this KA9Q receiver.

    For local receivers: read the actual value from the radiod conf so
    the recorder connects to whatever name radiod is currently advertising.
    Falls back to the derived convention (<radiod_name>-status.local) when
    the conf file is absent.

    For remote receivers: always use the derived convention since we cannot
    read the remote conf.
    """
    derived = f'{receiver.radiod_name}-status.local' if receiver.radiod_name else ''

    if receiver.locality == 'local' and receiver.radiod_name:
        conf = Path(f'/etc/radio/radiod@{receiver.radiod_name}.conf')
        if conf.exists():
            for raw in conf.read_text().splitlines():
                line = raw.strip()
                if line.startswith('#'):
                    continue
                m = re.match(r'^status\s*=\s*(\S+)', line)
                if m:
                    actual = m.group(1)
                    # Only warn when the conf's status name doesn't even
                    # start with the radiod_name — that case suggests the
                    # operator pointed the receiver at a different radiod.
                    # Names that just add a suffix (e.g. -hf) for antenna
                    # disambiguation are fine and shouldn't generate noise
                    # on every apply.
                    actual_base = actual.removesuffix('.local').removesuffix('.status')
                    if (actual_base != receiver.radiod_name
                            and not actual_base.startswith(receiver.radiod_name + '-')
                            and derived):
                        import sys
                        print(f'  WARNING: radiod@{receiver.radiod_name}: '
                              f'status={actual!r} does not match radiod_name '
                              f'(expected something like {derived!r})',
                              file=sys.stderr)
                    return actual
        return derived

    return derived

# WSPR band center frequencies in Hz (for wsprd and jt9)
BAND_FREQ_HZ = {
    '2200':   136000,
    '630':    474200,
    '160':   1836600,
    '80':    3568600,
    '80eu':  3592600,
    '60':    5287200,
    '60eu':  5364700,
    '40':    7038600,
    '30':   10138700,
    '22':   13553900,
    '20':   14095600,
    '17':   18104600,
    '15':   21094600,
    '12':   24924600,
    '10':   28124600,
    # VHF experimental + 6m
    # 8m: UK Ofcom experimental allocation 40.660-40.700 MHz; WSJT-X
    # places WSPR's carrier at 40.680400 MHz (1.5 kHz audio offset
    # above the 40.679 MHz dial).  EU stations report on this band.
    '8':    40680400,
    # 6m: WSPR carrier at 50.293000 MHz.  Sporadic-E + meteor scatter
    # producer; long quiet stretches between band openings are normal.
    '6':    50293000,
    # WWV/CHU bands (IQ recording)
    'WWV_2_5':  2500000,
    'WWV_5':    5000000,
    'WWV_10':  10000000,
    'WWV_15':  15000000,
    'WWV_20':  20000000,
    'WWV_25':  25000000,
    'CHU_3':    3330000,
    'CHU_7':    7850000,
    'CHU_14':  14670000,
}


def _env_header() -> str:
    return '# Auto-generated by wd-ctl — do not edit manually\n'


def generate_ka9q_record_env(receiver: Receiver,
                              bands: Set[str],
                              band_modes: Dict[str, set]) -> str:
    """Generate env file for a KA9Q recording service.

    KA9Q recorders are 1-to-N: one process uses ka9q-python to dynamically
    create channels on radiod and write wav files for all component bands.
    """
    status_dns = _radiod_status_dns(receiver)
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_TYPE={receiver.receiver_type}')
    lines.append(f'WD_KA9Q_LOCALITY={receiver.locality}')
    lines.append(f'WD_KA9Q_RADIOD_NAME={receiver.radiod_name}')
    lines.append(f'WD_RADIOD_STATUS={status_dns}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECORDING_DIR={paths.receiver_recording_dir(receiver.name)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_RUN_DIR={paths.RUN_DIR}')
    sorted_bands = sorted(bands, key=lambda b: BAND_FREQ_HZ.get(b, 0))
    lines.append(f'WD_BANDS={" ".join(sorted_bands)}')
    return '\n'.join(lines) + '\n'


def generate_kiwi_record_env(receiver: Receiver,
                              band: str,
                              modes: str) -> str:
    """Generate env file for a Kiwi recording service instance.

    Kiwi recorders are 1:1 — one kiwi_recorder.py per channel/band.
    """
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_TYPE=kiwi')
    lines.append(f'WD_KIWI_ADDRESS={receiver.address}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECEIVER_BAND={band}')
    lines.append(f'WD_RECEIVER_MODES={modes}')
    freq = BAND_FREQ_HZ.get(band, 0)
    lines.append(f'WD_RECEIVER_FREQ_HZ={freq}')
    pw = receiver.password if receiver.password != 'NULL' else ''
    lines.append(f'WD_KIWI_PASSWORD={pw}')
    lines.append(f'WD_RECORDING_DIR={paths.band_recording_dir(receiver.name, band)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_RUN_DIR={paths.RUN_DIR}')
    return '\n'.join(lines) + '\n'


def generate_decode_env(receiver: Receiver,
                        band: str,
                        modes: str) -> str:
    """Generate env file for a decode service instance."""
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_TYPE={receiver.receiver_type}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECEIVER_BAND={band}')
    lines.append(f'WD_RECEIVER_MODES={modes}')
    freq = BAND_FREQ_HZ.get(band, 0)
    lines.append(f'WD_RECEIVER_FREQ_HZ={freq}')
    lines.append(f'WD_RECORDING_DIR={paths.band_recording_dir(receiver.name, band)}')
    lines.append(f'WD_POSTING_DIR={paths.band_posting_dir(receiver.name, band)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_RUN_DIR={paths.RUN_DIR}')
    return '\n'.join(lines) + '\n'


def generate_post_env(receiver: Receiver,
                      band: str,
                      modes: str,
                      upload_wsprnet: bool = True,
                      upload_wsprdaemon: bool = True) -> str:
    """Generate env file for a posting service instance."""
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_NAME={receiver.name}')
    lines.append(f'WD_RECEIVER_CALL={receiver.call}')
    lines.append(f'WD_RECEIVER_GRID={receiver.grid}')
    lines.append(f'WD_RECEIVER_BAND={band}')
    lines.append(f'WD_POSTING_DIR={paths.band_posting_dir(receiver.name, band)}')
    if upload_wsprnet:
        lines.append(f'WD_UPLOAD_WSPRNET_DIR={paths.upload_dir("wsprnet", receiver.call, receiver.grid)}')
    if upload_wsprdaemon:
        lines.append(f'WD_UPLOAD_WSPRDAEMON_DIR={paths.upload_dir("wsprdaemon", receiver.call, receiver.grid, receiver.name, band)}')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    return '\n'.join(lines) + '\n'


def generate_upload_wsprnet_env(call: str, grid: str) -> str:
    """Generate env file for a wsprnet upload service instance (one per call+grid)."""
    safe_call = call.replace('/', '=')
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_CALL={call}')
    lines.append(f'WD_RECEIVER_GRID={grid}')
    lines.append(f'WD_UPLOAD_WSPRNET_DIR={paths.upload_dir("wsprnet", call, grid)}')
    lines.append(f'WD_VERSION=4.0')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    lines.append(f'WD_DIAGNOSTIC_UPLOAD=1')
    return '\n'.join(lines) + '\n'


def generate_upload_wsprdaemon_env(call: str, grid: str) -> str:
    """Generate env file for a wsprdaemon upload service instance (one per call+grid)."""
    safe_call = call.replace('/', '=')
    base_upload_dir = paths.POSTING_DIR / 'uploads' / 'wsprdaemon' / safe_call
    lines = [_env_header()]
    lines.append(f'WD_RECEIVER_CALL={call}')
    lines.append(f'WD_RECEIVER_GRID={grid}')
    lines.append(f'WD_UPLOAD_WSPRDAEMON_DIR={base_upload_dir}')
    lines.append(f'WD_VERSION=4.0')
    lines.append(f'WD_LOG_DIR={paths.LOG_DIR}')
    return '\n'.join(lines) + '\n'


def generate_all_env_files(config: WdConfig, output_dir: Path) -> List[str]:
    """Generate all environment files from a parsed v3 config.

    Returns a list of file paths that were written.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    written = []

    # Collect which receivers actually appear in the schedule
    # and what bands/modes they use
    rx_band_modes: Dict[str, Dict[str, str]] = {}  # rx_name → {band → modes_str}

    for slot in config.schedule_slots:
        for entry in slot.entries:
            rx_name = entry.receiver
            if rx_name not in rx_band_modes:
                rx_band_modes[rx_name] = {}
            # Merge mode lists across schedule entries, preserving config order.
            # Use an ordered deduplication: existing modes first (in their order),
            # then any modes from the new entry not already present.
            # sorted() must NOT be used here — it alphabetises W2:F2:F5 → F2:F5:W2,
            # causing W2 (wsprd) to run last instead of first.
            existing = rx_band_modes[rx_name].get(entry.band)
            existing_modes = existing.split(':') if existing else []
            seen: set = set(existing_modes)
            combined = existing_modes[:]
            for m in entry.modes.split(':'):
                if m and m not in seen:
                    combined.append(m)
                    seen.add(m)
            rx_band_modes[rx_name][entry.band] = ':'.join(combined)

    # Expand merge sources: every band assigned to a merge receiver must also
    # be recorded by each component source receiver.  The merge only happens
    # after decoding — all sources record independently.
    for rx_name in list(rx_band_modes.keys()):
        rx = config.receivers.get(rx_name)
        if rx is None or not rx.is_merge:
            continue
        for src_name in rx.merge_sources:
            src_rx = config.receivers.get(src_name)
            if src_rx is None:
                continue
            if src_name not in rx_band_modes:
                rx_band_modes[src_name] = {}
            for band, modes in rx_band_modes[rx_name].items():
                existing = rx_band_modes[src_name].get(band, '')
                existing_set = set(existing.split(':')) - {''} if existing else set()
                new_set = set(modes.split(':')) - {''}
                rx_band_modes[src_name][band] = ':'.join(sorted(existing_set | new_set))

    for rx_name, band_map in rx_band_modes.items():
        rx = config.receivers.get(rx_name)
        if not rx:
            continue

        if rx.receiver_type == 'ka9q':
            # KA9Q recorder — one env file per receiver
            env_path = output_dir / f'wd-ka9q-record@{rx_name}.env'
            env_path.write_text(generate_ka9q_record_env(
                rx, set(band_map.keys()), config.band_modes
            ))
            written.append(str(env_path))

            # Decode env — one per receiver+band
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-decode@{inst}.env'
                env_path.write_text(generate_decode_env(rx, band, modes))
                written.append(str(env_path))

                env_path = output_dir / f'wd-post@{inst}.env'
                env_path.write_text(generate_post_env(rx, band, modes))
                written.append(str(env_path))

        elif rx.receiver_type == 'ka9q_wwv':
            # WWV/CHU IQ recording — one env per receiver
            env_path = output_dir / f'wd-ka9q-record@{rx_name}.env'
            env_path.write_text(generate_ka9q_record_env(
                rx, set(band_map.keys()), config.band_modes
            ))
            written.append(str(env_path))

            # IQ decode instances
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-decode@{inst}.env'
                env_path.write_text(generate_decode_env(rx, band, modes))
                written.append(str(env_path))

        elif rx.receiver_type == 'kiwi':
            # Kiwi recorder — one env per receiver+band
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-kiwi-record@{inst}.env'
                env_path.write_text(generate_kiwi_record_env(rx, band, modes))
                written.append(str(env_path))

                env_path = output_dir / f'wd-decode@{inst}.env'
                env_path.write_text(generate_decode_env(rx, band, modes))
                written.append(str(env_path))

                env_path = output_dir / f'wd-post@{inst}.env'
                env_path.write_text(generate_post_env(rx, band, modes))
                written.append(str(env_path))

        elif rx.receiver_type == 'merge':
            # Merge receivers — decode/post env only (recording comes from sources)
            for band, modes in band_map.items():
                inst = f'{rx_name}-{band}'
                env_path = output_dir / f'wd-decode@{inst}.env'
                content = generate_decode_env(rx, band, modes)
                # Add merge source list
                content += f'WD_MERGE_SOURCES={rx.address}\n'
                env_path.write_text(content)
                written.append(str(env_path))

                env_path = output_dir / f'wd-post@{inst}.env'
                env_path.write_text(generate_post_env(rx, band, modes))
                written.append(str(env_path))

    # --- Upload env files: one per unique (call, grid) pair ---
    seen_uploaders: set = set()
    for rx in config.receivers.values():
        if rx.receiver_type not in ('ka9q', 'ka9q_wwv', 'kiwi', 'merge'):
            continue
        if not rx.call or not rx.grid:
            continue
        key = (rx.call, rx.grid)
        if key in seen_uploaders:
            continue
        seen_uploaders.add(key)
        # Systemd instance names allow [a-zA-Z0-9_:.-] only — '/' (as in
        # AC0G/B4 portable-suffix callsigns) and '=' are both rejected.
        # Other call sites in this module use '=' for filesystem path
        # encoding where '=' is valid; here the value flows into a unit
        # name, so we use '-' instead.  See wd-upload@*.service template.
        safe_call = rx.call.replace('/', '-')
        instance = f'{safe_call}_{rx.grid}'

        env_path = output_dir / f'wd-upload-wsprnet@{instance}.env'
        env_path.write_text(generate_upload_wsprnet_env(rx.call, rx.grid))
        written.append(str(env_path))

        env_path = output_dir / f'wd-upload-wsprdaemon@{instance}.env'
        env_path.write_text(generate_upload_wsprdaemon_env(rx.call, rx.grid))
        written.append(str(env_path))

    return written
