"""Convert a parsed v3 config dict into a v4 INI config file.

Usage::

    from wdlib.v3_parser import parse_v3_config
    from wdlib.ini_writer import write_v4_ini

    v3 = parse_v3_config('/path/to/wsprdaemon.conf')
    ini_text = write_v4_ini(v3)
    Path('/etc/wsprdaemon/wsprdaemon.conf').write_text(ini_text)
"""

from typing import Dict, List


def write_v4_ini(v3_data: dict) -> str:
    """Render a v4 INI config string from a parsed v3 data dict."""
    hostname = v3_data.get('hostname', '')
    receivers = v3_data.get('receivers', [])
    settings  = v3_data.get('host_settings', {})
    schedule  = v3_data.get('schedule', [])

    lines: List[str] = []

    lines.append(f'# Generated by wd-ctl migrate-config from wsprdaemon.conf (v3)')
    lines.append(f'# Source hostname: {hostname}')
    lines.append('')

    # ── [general] ─────────────────────────────────────────────────────────────
    lines.append('[general]')
    if settings.get('ka9q_conf_name'):
        lines.append(f"ka9q_conf_name = {settings['ka9q_conf_name']}")
    if settings.get('rac'):
        lines.append(f"rac = {settings['rac']}")
    lines.append('')

    # ── Collect band→modes per receiver from the schedule ─────────────────────
    # rx_band_modes[rx][band] = modes  (colon-separated, v3 style)
    rx_band_modes: Dict[str, Dict[str, str]] = {}
    # rx_bands_ordered[rx] = [band, ...] preserving first-seen order
    rx_bands_ordered: Dict[str, List[str]] = {}

    for slot in schedule:
        for entry in slot['entries']:
            rx   = entry['receiver']
            band = entry['band']
            modes = entry['modes']
            if rx not in rx_band_modes:
                rx_band_modes[rx] = {}
                rx_bands_ordered[rx] = []
            if band not in rx_band_modes[rx]:
                rx_band_modes[rx][band] = modes
                rx_bands_ordered[rx].append(band)

    # ── [receiver:NAME] and [receiver:NAME:BAND] sections ─────────────────────
    rx_by_name = {r['name']: r for r in receivers}

    for rx in receivers:
        name = rx['name']
        is_merge = name.upper().startswith('MERG_')

        if is_merge:
            # MERG_ receivers → [merge:NAME]
            sources = rx['address'].replace(',', ' ')
            lines.append(f'[merge:{name}]')
            lines.append(f'sources = {sources}')
            lines.append(f"call = {rx['call']}")
            lines.append(f"grid = {rx['grid']}")
            lines.append('')

            # Band mode sections for merge (if it appears in the schedule)
            for band in rx_bands_ordered.get(name, []):
                modes_colon = rx_band_modes[name][band]
                modes_space = modes_colon.replace(':', ' ')
                lines.append(f'[merge:{name}:{band}]')
                lines.append(f'modes = {modes_space}')
                lines.append('')
        else:
            # Normal KA9Q / Kiwi receivers → [receiver:NAME]
            lines.append(f'[receiver:{name}]')
            lines.append(f"address = {rx['address']}")
            lines.append(f"call = {rx['call']}")
            lines.append(f"grid = {rx['grid']}")
            lines.append(f"password = {rx['password']}")
            lines.append('')

            # Band mode sections (only for bands that appear in the schedule)
            for band in rx_bands_ordered.get(name, []):
                modes_colon = rx_band_modes[name][band]
                modes_space = modes_colon.replace(':', ' ')
                lines.append(f'[receiver:{name}:{band}]')
                lines.append(f'modes = {modes_space}')
                lines.append('')

    # ── [schedule:LABEL] sections ─────────────────────────────────────────────
    # Group slots by time label; use 'main' for the single common case
    for i, slot in enumerate(schedule):
        label = 'main' if len(schedule) == 1 else f'slot{i}'
        lines.append(f'[schedule:{label}]')
        lines.append(f"time = {slot['time']}")

        # Group entries by receiver to emit one key per receiver
        rx_bands_in_slot: Dict[str, List[str]] = {}
        for entry in slot['entries']:
            rx   = entry['receiver']
            band = entry['band']
            rx_bands_in_slot.setdefault(rx, []).append(band)

        for rx, bands in rx_bands_in_slot.items():
            lines.append(f'{rx} = {" ".join(bands)}')

        lines.append('')

    # ── Unmapped v3 settings as comments ──────────────────────────────────────
    unmapped = {
        k: v for k, v in settings.items()
        if k not in ('ka9q_conf_name', 'rac')
    }
    if unmapped:
        lines.append('# --- Settings from v3 config not yet mapped to v4 ---')
        for k, v in unmapped.items():
            lines.append(f'# {k} = {v}')
        lines.append('')

    return '\n'.join(lines)
